
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mokleters
 */
public class pembayaran extends javax.swing.JFrame {

    /**
     * Creates new form pembayaran
     */
    public pembayaran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namabayar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tanggal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        notelp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        hitunghari = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        totalbayar = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        bersihkan = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel2.setText("PEMBAYARAN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 10, 180, 30);

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel3.setText("Nama Pembayar");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 60, 180, 30);
        getContentPane().add(namabayar);
        namabayar.setBounds(150, 60, 370, 30);

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel4.setText("Tanggal");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 100, 180, 30);
        getContentPane().add(tanggal);
        tanggal.setBounds(150, 100, 370, 30);

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel9.setText("No. Telp");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 180, 180, 30);
        getContentPane().add(notelp);
        notelp.setBounds(150, 180, 370, 30);

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel6.setText("Jenis/Tipe Home");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 220, 110, 30);

        jRadioButton2.setText("Kelas I");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(150, 230, 57, 23);

        jRadioButton3.setText("Kelas II");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(150, 260, 70, 23);

        jRadioButton1.setText("VIP");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(150, 290, 50, 23);

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel1.setText("Hitungan Hari");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 140, 180, 30);
        getContentPane().add(hitunghari);
        hitunghari.setBounds(150, 140, 370, 30);

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel8.setText("Total Bayar");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 320, 80, 30);
        getContentPane().add(totalbayar);
        totalbayar.setBounds(150, 320, 370, 30);

        hitung.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung);
        hitung.setBounds(20, 370, 120, 30);

        bersihkan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bersihkan.setText("Bersihkan");
        bersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanActionPerformed(evt);
            }
        });
        getContentPane().add(bersihkan);
        bersihkan.setBounds(170, 370, 120, 30);

        kembali.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali);
        kembali.setBounds(20, 410, 120, 30);

        keluar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(170, 410, 120, 30);

        setBounds(0, 0, 585, 498);
    }// </editor-fold>//GEN-END:initComponents

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hitungActionPerformed

    private void bersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkanActionPerformed
String x=JOptionPane.showInputDialog(null, "Masukan Kode Barang");
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:81/ta_pbo", "root", "");
            Statement stat=connection.createStatement();
            String del="Delete FROM sewa WHERE kode_transaksi='"+x+"'";
            stat.executeUpdate(del);
            JOptionPane.showMessageDialog(rootPane, "Data Terhapus");
            
            namabayar.setText("");
            tanggal.setText("");
            hitunghari.setText("");
            notelp.setText("");
            totalbayar.setText("");
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Koeksi Gagal"+e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bersihkanActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bersihkan;
    private javax.swing.JButton hitung;
    private javax.swing.JTextField hitunghari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JButton keluar;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField namabayar;
    private javax.swing.JTextField notelp;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTextField totalbayar;
    // End of variables declaration//GEN-END:variables
}
