
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mokleters
 */
public class sewa extends javax.swing.JFrame {
    /**
     * Creates new form
     */
    public sewa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kode = new javax.swing.JTextField();
        tanggal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namasewa = new javax.swing.JTextField();
        nokamar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        hargasewa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        select = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        ulangi = new javax.swing.JButton();
        cari = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        notelp = new javax.swing.JTextField();
        fasilitas = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lokasi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        simpan = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel2.setText("SELAMAT DATANG");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 10, 180, 30);

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel3.setText("Kode Transaksi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 60, 120, 30);
        getContentPane().add(kode);
        kode.setBounds(150, 60, 370, 30);
        getContentPane().add(tanggal);
        tanggal.setBounds(150, 100, 370, 30);

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel4.setText("Tanggal");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 100, 110, 30);

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel5.setText("Nama Penyewa");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 140, 110, 30);
        getContentPane().add(namasewa);
        namasewa.setBounds(150, 140, 370, 30);
        getContentPane().add(nokamar);
        nokamar.setBounds(150, 180, 370, 30);

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel7.setText("No Kamar");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 180, 110, 30);

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel1.setText("Alamat");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 220, 100, 30);
        getContentPane().add(alamat);
        alamat.setBounds(150, 220, 370, 30);
        getContentPane().add(hargasewa);
        hargasewa.setBounds(150, 470, 370, 30);

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel6.setText("Jenis/Tipe Home");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 300, 110, 30);

        select.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        select.setText("Pembayaran");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        getContentPane().add(select);
        select.setBounds(560, 60, 120, 30);

        menu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        menu.setText("Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu);
        menu.setBounds(560, 100, 120, 30);

        ulangi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ulangi.setText("Ulangi");
        ulangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulangiActionPerformed(evt);
            }
        });
        getContentPane().add(ulangi);
        ulangi.setBounds(560, 180, 120, 30);

        cari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cari.setText("Pencarian");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari);
        cari.setBounds(560, 140, 120, 30);

        edit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit);
        edit.setBounds(560, 340, 120, 30);

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel8.setText("Harga Sewa");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 470, 80, 30);

        jRadioButton1.setText("VIP");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(430, 300, 41, 23);

        jRadioButton2.setText("Kelas I");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(150, 303, 90, 20);

        jRadioButton3.setText("Kelas II");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(280, 300, 70, 23);

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel9.setText("No. Telp");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 260, 110, 30);

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel10.setText("Fasilitas");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 340, 100, 30);
        getContentPane().add(notelp);
        notelp.setBounds(150, 260, 370, 30);
        getContentPane().add(fasilitas);
        fasilitas.setBounds(150, 340, 370, 60);

        jLabel11.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel11.setText("Lokasi");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 410, 100, 30);
        getContentPane().add(lokasi);
        lokasi.setBounds(150, 410, 370, 50);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Transaksi", "Tanggal", "Nama Penyewa", "No Kamar", "Alamat", "No Telp", "Fasilitas", "Lokasi", "Harga Sewa"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 510, 810, 160);

        simpan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan);
        simpan.setBounds(560, 410, 120, 30);

        keluar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(560, 470, 120, 30);

        update.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(560, 300, 120, 30);

        setBounds(0, 0, 855, 729);
    }// </editor-fold>//GEN-END:initComponents

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        new pembayaran().show();
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_selectActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
         new menu_utama().show();
         this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void ulangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulangiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ulangiActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_cariActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        int bismillah=JOptionPane.showConfirmDialog(null,"Yakin Mengubah?","Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:81/ta_pbo", "root","");
            Statement stat=connection.createStatement();
            String sqlnya="update kode_transaksi=?, tanggal=?, nama_penyewa=?, no_kamar=?, alamat=?, no_telp" + "kode_transaksi='"+kode.getText()+"'";
            PreparedStatement st=connection.prepareStatement(sqlnya);
            
            if(bismillah==0){
                
                try{
                st.setString(1,kode.getText());
                st.setString(2,tanggal.getText());
                st.setString(3,namasewa.getText());
                st.setString(4,nokamar.getText());
                st.setString(5,alamat.getText());
                st.setString(6,notelp.getText());
                st.setString(7,fasilitas.getText());
                st.setString(8,lokasi.getText());
                st.setString(9,hargasewa.getText());
                st.executeUpdate();
                LoadData();
                JOptionPane.showMessageDialog(null,"Update Data Sukses");
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Update Data Gagal"+e);
            }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(sewa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(sewa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:81/ta_pbo");
            Statement stat=connection.createStatement();
            String sqlnya="INSERT INTO sewa VALUES ('"+kode.getText()+"','"+tanggal.getText()+"','"+namasewa.getText()
                    +"','"+nokamar.getText()+"','"+alamat.getText()+"','"+notelp.getText()+"','"+fasilitas.getText()
                    +"','"+lokasi.getText()+"','"+hargasewa.getText()+"')";
            stat.executeUpdate(sqlnya);
            LoadData();
            JOptionPane.showMessageDialog(rootPane, "Bisa");
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "coba lagi"+e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_simpanActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton cari;
    private javax.swing.JButton edit;
    private javax.swing.JTextField fasilitas;
    private javax.swing.JTextField hargasewa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kode;
    private javax.swing.JTextField lokasi;
    private javax.swing.JButton menu;
    private javax.swing.JTextField namasewa;
    private javax.swing.JTextField nokamar;
    private javax.swing.JTextField notelp;
    private javax.swing.JButton select;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tanggal;
    private javax.swing.JButton ulangi;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    private void LoadData() {
    }
}